spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb_prod
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false